services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db # MySQL service name as defined here
      DB_USER: root # MySQL root user
      DB_PASS: yourpassword # MySQL root password
      DB_NAME: wiki_app # Database name
      DB_PORT: 3306

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword # Root password for MySQL
      MYSQL_DATABASE: wiki_app # Default database name
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Persist data across container restarts

volumes:
  db_data:
